/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as CockpitRouteImport } from './routes/cockpit'
import { Route as CompanyBrainRouteImport } from './routes/company-brain'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CopilotsRouteImport } from './routes/copilots'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as HeatIntelligenceRouteImport } from './routes/heat-intelligence'
import { Route as HrRouteImport } from './routes/hr'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as LogisticsRouteImport } from './routes/logistics'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as MtcRouteImport } from './routes/mtc'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as WorkflowStudioRouteImport } from './routes/workflow-studio'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as AgentsSlugRouteImport } from './routes/agents/$slug'
import { Route as DepartmentsIndexRouteImport } from './routes/departments/index'
import { Route as DepartmentsSlugRouteImport } from './routes/departments/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const CockpitRoute = CockpitRouteImport.update({
  id: '/cockpit',
  path: '/cockpit',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyBrainRoute = CompanyBrainRouteImport.update({
  id: '/company-brain',
  path: '/company-brain',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotsRoute = CopilotsRouteImport.update({
  id: '/copilots',
  path: '/copilots',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatIntelligenceRoute = HeatIntelligenceRouteImport.update({
  id: '/heat-intelligence',
  path: '/heat-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsRoute = LogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const MtcRoute = MtcRouteImport.update({
  id: '/mtc',
  path: '/mtc',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowStudioRoute = WorkflowStudioRouteImport.update({
  id: '/workflow-studio',
  path: '/workflow-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsSlugRoute = AgentsSlugRouteImport.update({
  id: '/agents/$slug',
  path: '/agents/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsIndexRoute = DepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsSlugRoute = DepartmentsSlugRouteImport.update({
  id: '/departments/$slug',
  path: '/departments/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/automation': typeof AutomationRoute
  '/cockpit': typeof CockpitRoute
  '/company-brain': typeof CompanyBrainRoute
  '/compliance': typeof ComplianceRoute
  '/copilots': typeof CopilotsRoute
  '/customers': typeof CustomersRoute
  '/documents': typeof DocumentsRoute
  '/finance': typeof FinanceRoute
  '/governance': typeof GovernanceRoute
  '/heat-intelligence': typeof HeatIntelligenceRoute
  '/hr': typeof HrRoute
  '/integrations': typeof IntegrationsRoute
  '/inventory': typeof InventoryRoute
  '/knowledge': typeof KnowledgeRoute
  '/logistics': typeof LogisticsRoute
  '/materials': typeof MaterialsRoute
  '/mtc': typeof MtcRoute
  '/production': typeof ProductionRoute
  '/projects': typeof ProjectsRoute
  '/quality': typeof QualityRoute
  '/reports': typeof ReportsRoute
  '/risk': typeof RiskRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/vendors': typeof VendorsRoute
  '/workflow-studio': typeof WorkflowStudioRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/departments/$slug': typeof DepartmentsSlugRoute
  '/agents/': typeof AgentsIndexRoute
  '/departments/': typeof DepartmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/automation': typeof AutomationRoute
  '/cockpit': typeof CockpitRoute
  '/company-brain': typeof CompanyBrainRoute
  '/compliance': typeof ComplianceRoute
  '/copilots': typeof CopilotsRoute
  '/customers': typeof CustomersRoute
  '/documents': typeof DocumentsRoute
  '/finance': typeof FinanceRoute
  '/governance': typeof GovernanceRoute
  '/heat-intelligence': typeof HeatIntelligenceRoute
  '/hr': typeof HrRoute
  '/integrations': typeof IntegrationsRoute
  '/inventory': typeof InventoryRoute
  '/knowledge': typeof KnowledgeRoute
  '/logistics': typeof LogisticsRoute
  '/materials': typeof MaterialsRoute
  '/mtc': typeof MtcRoute
  '/production': typeof ProductionRoute
  '/projects': typeof ProjectsRoute
  '/quality': typeof QualityRoute
  '/reports': typeof ReportsRoute
  '/risk': typeof RiskRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/vendors': typeof VendorsRoute
  '/workflow-studio': typeof WorkflowStudioRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/departments/$slug': typeof DepartmentsSlugRoute
  '/agents': typeof AgentsIndexRoute
  '/departments': typeof DepartmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/automation': typeof AutomationRoute
  '/cockpit': typeof CockpitRoute
  '/company-brain': typeof CompanyBrainRoute
  '/compliance': typeof ComplianceRoute
  '/copilots': typeof CopilotsRoute
  '/customers': typeof CustomersRoute
  '/documents': typeof DocumentsRoute
  '/finance': typeof FinanceRoute
  '/governance': typeof GovernanceRoute
  '/heat-intelligence': typeof HeatIntelligenceRoute
  '/hr': typeof HrRoute
  '/integrations': typeof IntegrationsRoute
  '/inventory': typeof InventoryRoute
  '/knowledge': typeof KnowledgeRoute
  '/logistics': typeof LogisticsRoute
  '/materials': typeof MaterialsRoute
  '/mtc': typeof MtcRoute
  '/production': typeof ProductionRoute
  '/projects': typeof ProjectsRoute
  '/quality': typeof QualityRoute
  '/reports': typeof ReportsRoute
  '/risk': typeof RiskRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/vendors': typeof VendorsRoute
  '/workflow-studio': typeof WorkflowStudioRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/departments/$slug': typeof DepartmentsSlugRoute
  '/agents/': typeof AgentsIndexRoute
  '/departments/': typeof DepartmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administration'
    | '/analytics'
    | '/approvals'
    | '/automation'
    | '/cockpit'
    | '/company-brain'
    | '/compliance'
    | '/copilots'
    | '/customers'
    | '/documents'
    | '/finance'
    | '/governance'
    | '/heat-intelligence'
    | '/hr'
    | '/integrations'
    | '/inventory'
    | '/knowledge'
    | '/logistics'
    | '/materials'
    | '/mtc'
    | '/production'
    | '/projects'
    | '/quality'
    | '/reports'
    | '/risk'
    | '/security'
    | '/settings'
    | '/tasks'
    | '/vendors'
    | '/workflow-studio'
    | '/agents/$slug'
    | '/departments/$slug'
    | '/agents/'
    | '/departments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administration'
    | '/analytics'
    | '/approvals'
    | '/automation'
    | '/cockpit'
    | '/company-brain'
    | '/compliance'
    | '/copilots'
    | '/customers'
    | '/documents'
    | '/finance'
    | '/governance'
    | '/heat-intelligence'
    | '/hr'
    | '/integrations'
    | '/inventory'
    | '/knowledge'
    | '/logistics'
    | '/materials'
    | '/mtc'
    | '/production'
    | '/projects'
    | '/quality'
    | '/reports'
    | '/risk'
    | '/security'
    | '/settings'
    | '/tasks'
    | '/vendors'
    | '/workflow-studio'
    | '/agents/$slug'
    | '/departments/$slug'
    | '/agents'
    | '/departments'
  id:
    | '__root__'
    | '/'
    | '/administration'
    | '/analytics'
    | '/approvals'
    | '/automation'
    | '/cockpit'
    | '/company-brain'
    | '/compliance'
    | '/copilots'
    | '/customers'
    | '/documents'
    | '/finance'
    | '/governance'
    | '/heat-intelligence'
    | '/hr'
    | '/integrations'
    | '/inventory'
    | '/knowledge'
    | '/logistics'
    | '/materials'
    | '/mtc'
    | '/production'
    | '/projects'
    | '/quality'
    | '/reports'
    | '/risk'
    | '/security'
    | '/settings'
    | '/tasks'
    | '/vendors'
    | '/workflow-studio'
    | '/agents/$slug'
    | '/departments/$slug'
    | '/agents/'
    | '/departments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministrationRoute: typeof AdministrationRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AutomationRoute: typeof AutomationRoute
  CockpitRoute: typeof CockpitRoute
  CompanyBrainRoute: typeof CompanyBrainRoute
  ComplianceRoute: typeof ComplianceRoute
  CopilotsRoute: typeof CopilotsRoute
  CustomersRoute: typeof CustomersRoute
  DocumentsRoute: typeof DocumentsRoute
  FinanceRoute: typeof FinanceRoute
  GovernanceRoute: typeof GovernanceRoute
  HeatIntelligenceRoute: typeof HeatIntelligenceRoute
  HrRoute: typeof HrRoute
  IntegrationsRoute: typeof IntegrationsRoute
  InventoryRoute: typeof InventoryRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LogisticsRoute: typeof LogisticsRoute
  MaterialsRoute: typeof MaterialsRoute
  MtcRoute: typeof MtcRoute
  ProductionRoute: typeof ProductionRoute
  ProjectsRoute: typeof ProjectsRoute
  QualityRoute: typeof QualityRoute
  ReportsRoute: typeof ReportsRoute
  RiskRoute: typeof RiskRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  VendorsRoute: typeof VendorsRoute
  WorkflowStudioRoute: typeof WorkflowStudioRoute
  AgentsSlugRoute: typeof AgentsSlugRoute
  DepartmentsSlugRoute: typeof DepartmentsSlugRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  DepartmentsIndexRoute: typeof DepartmentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cockpit': {
      id: '/cockpit'
      path: '/cockpit'
      fullPath: '/cockpit'
      preLoaderRoute: typeof CockpitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-brain': {
      id: '/company-brain'
      path: '/company-brain'
      fullPath: '/company-brain'
      preLoaderRoute: typeof CompanyBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilots': {
      id: '/copilots'
      path: '/copilots'
      fullPath: '/copilots'
      preLoaderRoute: typeof CopilotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heat-intelligence': {
      id: '/heat-intelligence'
      path: '/heat-intelligence'
      fullPath: '/heat-intelligence'
      preLoaderRoute: typeof HeatIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics': {
      id: '/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof LogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mtc': {
      id: '/mtc'
      path: '/mtc'
      fullPath: '/mtc'
      preLoaderRoute: typeof MtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow-studio': {
      id: '/workflow-studio'
      path: '/workflow-studio'
      fullPath: '/workflow-studio'
      preLoaderRoute: typeof WorkflowStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$slug': {
      id: '/agents/$slug'
      path: '/agents/$slug'
      fullPath: '/agents/$slug'
      preLoaderRoute: typeof AgentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/': {
      id: '/departments/'
      path: '/departments'
      fullPath: '/departments/'
      preLoaderRoute: typeof DepartmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/$slug': {
      id: '/departments/$slug'
      path: '/departments/$slug'
      fullPath: '/departments/$slug'
      preLoaderRoute: typeof DepartmentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministrationRoute: AdministrationRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApprovalsRoute: ApprovalsRoute,
  AutomationRoute: AutomationRoute,
  CockpitRoute: CockpitRoute,
  CompanyBrainRoute: CompanyBrainRoute,
  ComplianceRoute: ComplianceRoute,
  CopilotsRoute: CopilotsRoute,
  CustomersRoute: CustomersRoute,
  DocumentsRoute: DocumentsRoute,
  FinanceRoute: FinanceRoute,
  GovernanceRoute: GovernanceRoute,
  HeatIntelligenceRoute: HeatIntelligenceRoute,
  HrRoute: HrRoute,
  IntegrationsRoute: IntegrationsRoute,
  InventoryRoute: InventoryRoute,
  KnowledgeRoute: KnowledgeRoute,
  LogisticsRoute: LogisticsRoute,
  MaterialsRoute: MaterialsRoute,
  MtcRoute: MtcRoute,
  ProductionRoute: ProductionRoute,
  ProjectsRoute: ProjectsRoute,
  QualityRoute: QualityRoute,
  ReportsRoute: ReportsRoute,
  RiskRoute: RiskRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  VendorsRoute: VendorsRoute,
  WorkflowStudioRoute: WorkflowStudioRoute,
  AgentsSlugRoute: AgentsSlugRoute,
  DepartmentsSlugRoute: DepartmentsSlugRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  DepartmentsIndexRoute: DepartmentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
